// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebase: {
    apiKey: 'AIzaSyAw4wbgPlIr_2r5yshD5morui9ManW2Ydw',
    authDomain: 'numbers-multiples.firebaseapp.com',
    databaseURL: 'https://numbers-multiples.firebaseio.com',
    projectId: 'numbers-multiples',
    storageBucket: 'numbers-multiples.appspot.com',
    messagingSenderId: '676748286005',
    appId: '1:676748286005:web:f05f7d263bbab96f70397c',
  },
};
